### ISSUE TITLE
[Feature] PC (Windows) game install support

### ISSUE THREAD

**Issue by outerwinnie** [rommapp/playnite-plugin#29]
Hi, does the plugin have PC (Windows) game installation support? If so, how does it work? I have manage to detect and add the games to Playnite, download and unzip them but the exe has to be added manually for each game after unzipping. I have manage this by creating an empty emulator profile like this:
![imagen](https://github.com/user-attachments/assets/9d77b241-f5fc-4d7e-bfd7-38ee670a65b7)

Is there some workaround or something?

Thanks!

**Comment by wikewi** [comment]
I don't think it does and would some difficult to auto detect as most games have very different ways of installing the software. Just a suggestion and perhaps an easier workaround. How about adding a bat file (i.e. run.bat) when creating your game zip archives laybcges points the executable. Just give all games you compress the same title for the bat file. In that way you can launch all game by putting {InstallDir}\run.bat assuming you're calling the file run.bat and make this your default emulator profile, you could try with shortcuts as well but I believe windows doesn't store shortcuts with relative paths so if the exe file is in a subfolder that might give some issues.

**Comment by outerwinnie** [comment]
> I don't think it does and would some difficult to auto detect as most games have very different ways of installing the software. Just a suggestion and perhaps an easier workaround. How about adding a bat file (i.e. run.bat) when creating your game zip archives that points to the main game executable. Just give all games you compress the same title for the bat file. In that way you can launch all game by putting {InstallDir}\run.bat assuming you're calling the file run.bat and make this your default emulator profile, you could try with shortcuts as well but I believe windows doesn't store shortcuts with relative paths so if the exe file is in a subfolder that might give some issues.


This method seems to work pretty well, thanks!

**Comment by adamtiley** [comment]
Heya, sorry to revive this one, but with the above solution - is there any way to get it to stop duplicating the installation paths? 

It installs when I tell it to do so and works when I press play, but it also creates hundreds of run paths for each file that look like this:

<img width="1534" height="1541" alt="Image" src="https://github.com/user-attachments/assets/6771c599-c57d-4389-a3a3-8f868ae9caa4" />


Thanks :)

**Comment by adamtiley** [comment]
I've made a script to run on install that clears this out so no worries now :)
